version: "3"

services:
  redis:
    # container_name: backend_redis
    # network_mode: bridge
    image: redis
    restart: always
    ports:
      - 6380:6379

  postgres:
    # container_name: backend_postgres
    # network_mode: bridge
    image: postgres:alpine
    environment:
      - POSTGRES_DB=flipr
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: postgres -N 200
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432

  matchupdater:
    build:
      context: .
      dockerfile: Dockerfile.matchupdater
    depends_on: 
      - postgres
      - redis
      - fliprback
    # network_mode: bridge
    restart: always

  fliprback:
    build:
      context: .
      dockerfile: Dockerfile
    # network_mode: bridge
    depends_on: 
      - postgres
      - redis
    links: 
      - 'postgres:postgres'
      - 'redis:redis'
    restart: always
    ports:
      - 5000:5000

  nginx:
    image: nginx
    volumes:
      - ./docs:/usr/share/nginx/html
    ports: 
      - 8080:80

  nginxfrontend:
    image: nginx
    volumes:
      - ./build:/usr/share/nginx/html
    ports: 
      - 80:80