version: "3.3"

services:
  redis:
    container_name: backend_redis
    image: redis
    restart: always
    ports:
      - 6380:6379

  postgres:
    container_name: backend_postgres
    image: postgres:alpine
    environment:
      - POSTGRES_DB=flipr
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432

  matchupdater:
    build:
      context: .
      dockerfile: Dockerfile.matchupdater
    restart: always

  fliprback:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
